dockerize

diff --git a/rel/files/air b/rel/files/air
--- a/rel/files/air
+++ b/rel/files/air
@@ -1,20 +1,19 @@
-#!/bin/bash
+#!/bin/sh
 # -*- tab-width:4;indent-tabs-mode:nil -*-
 # ex: ts=4 sw=4 et
 
-find_erts_dir() {
-    local erts_dir="$RELEASE_ROOT_DIR/erts-$ERTS_VSN"
-    if [ -d "$erts_dir" ]; then
-        ERTS_DIR="$erts_dir";
-        ROOTDIR="$RELEASE_ROOT_DIR"
-    else
-        local erl="$(which erl)"
-        code="io:format(\"~s\", [code:root_dir()])."
-        local erl_root="$("$erl" -noshell -eval "$code" -s init stop)"
-        ERTS_DIR="$erl_root/erts-$ERTS_VSN"
-        ROOTDIR="$erl_root"
-    fi
-}
+# /bin/sh on Solaris is not a POSIX compatible shell, but /usr/bin/ksh is.
+if [ `uname -s` = 'SunOS' -a "${POSIX_SHELL}" != "true" ]; then
+    POSIX_SHELL="true"
+    export POSIX_SHELL
+    # To support 'whoami' add /usr/ucb to path
+    PATH=/usr/ucb:$PATH
+    export PATH
+    exec /usr/bin/ksh $0 "$@"
+fi
+
+# clear it so if we invoke other scripts, they run as ksh
+unset POSIX_SHELL
 
 RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd -P)
 RUNNER_SCRIPT=${0##*/}
@@ -87,6 +86,37 @@ fi
 REMSH_TYPE=`echo $NAME_ARG | awk '{print $1}'`
 REMSH_NAME=`echo $NAME_ARG | awk '{print $2}'`
 
+# Test if REMSH_NAME contains a @ and set REMSH_HOSTNAME_PART
+# and REMSH_NAME_PART according REMSH_TYPE
+MAYBE_FQDN_HOSTNAME=`hostname`
+HOSTNAME=`echo $MAYBE_FQDN_HOSTNAME | awk -F. '{print $1}'`
+
+REMSH_HOSTNAME_PART="$MAYBE_FQDN_HOSTNAME"
+case "$REMSH_NAME" in
+    *@*)
+        REMSH_HOSTNAME_PART=`echo $REMSH_NAME | awk -F@ '{print $2}'`
+        REMSH_NAME_PART=`echo $REMSH_NAME | awk -F@ '{print $1}'`
+        ;;
+    *)
+        REMSH_NAME_PART="$REMSH_NAME"
+        if [ "$REMSH_TYPE" = "-sname" ]; then
+            REMSH_HOSTNAME_PART="$HOSTNAME"
+        else
+            # -name type, check if `hostname` is fqdn
+            if [ "$MAYBE_FQDN_HOSTNAME" = "$HOSTNAME" ]; then
+                echo "Hostname must be a fqdn domain name when node is configured with long names"
+                echo "and the full node name isn't configured in vm.args"
+                exit 1
+            fi
+        fi
+        ;;
+esac
+
+# Note the `date +%s`, used to allow multiple remsh to the same node
+# transparently
+REMSH_NAME_ARG="$REMSH_TYPE remsh`date +%s`@$REMSH_HOSTNAME_PART"
+REMSH_REMSH_ARG="-remsh $REMSH_NAME_PART@$REMSH_HOSTNAME_PART"
+
 # Extract the target cookie
 COOKIE_ARG=`grep '^\-setcookie' $VMARGS_PATH`
 if [ -z "$COOKIE_ARG" ]; then
@@ -105,24 +135,41 @@ if [ -e "$RUNNER_BASE_DIR/releases/$APP_VSN/runner_script.data" ]; then
     RUNNER_SCRIPT_DATA=`cat $RUNNER_BASE_DIR/releases/$APP_VSN/runner_script.data`
 fi
 
-# Setup system paths
-SYSTEM_ERL_PATH=`which erl`
-if [ ! -x "$SYSTEM_ERL_PATH" ]; then
-    echo "Failed to find erl. Is Erlang/OTP available in PATH?"
+if [ -z "$RUNNER_SCRIPT_DATA" ]; then
+    ROOTDIR=$RUNNER_BASE_DIR
+    ERTS_PATH=$RUNNER_BASE_DIR/erts-$ERTS_VSN/bin
+    if [ -e "$RUNNER_BASE_DIR/releases/$APP_VSN/nodetool" ]; then
+        NODETOOL="$ERTS_PATH/escript $RUNNER_BASE_DIR/releases/$APP_VSN/nodetool $NAME_ARG $COOKIE_ARG"
+    else
+        NODETOOL="$ERTS_PATH/escript $ERTS_PATH/nodetool $NAME_ARG $COOKIE_ARG"
+    fi
+    SLIM_ARGS=
+elif [ "$RUNNER_SCRIPT_DATA" = "slim" ]; then
+    # Setup system paths
+    SYSTEM_ERL_PATH=`which erl`
+    if [ ! -x "$SYSTEM_ERL_PATH" ]; then
+        echo "Failed to find erl. Is Erlang/OTP available in PATH?"
+        exit 1
+    fi
+    SYSTEM_HOME_BIN=${SYSTEM_ERL_PATH%/*}
+    ROOTDIR=$SYSTEM_HOME_BIN/../lib/erlang
+    ERTS_PATH=$ROOTDIR/erts-$ERTS_VSN/bin
+    unset SYSTEM_ERL_PATH
+    unset SYSTEM_HOME_BIN
+
+    LOCAL_ERTS_PATH=$RUNNER_BASE_DIR/erts-$ERTS_VSN/bin
+    NODETOOL="$ERTS_PATH/escript $RUNNER_BASE_DIR/releases/$APP_VSN/nodetool $NAME_ARG $COOKIE_ARG"
+    unset LOCAL_ERL_PATH
+
+    # Setup additional arguments for slim release
+    SLIM_ARGS="-boot_var RELTOOL_EXT_LIB $RUNNER_BASE_DIR/lib -sasl releases_dir \"$RUNNER_BASE_DIR/releases\""
+else
+    echo "Unknown runner_script.data"
     exit 1
 fi
-SYSTEM_HOME_BIN=${SYSTEM_ERL_PATH%/*}
-find_erts_dir
-ERTS_PATH=$ROOTDIR/erts-$ERTS_VSN/bin
-unset SYSTEM_ERL_PATH
-unset SYSTEM_HOME_BIN
 
-LOCAL_ERTS_PATH=$RUNNER_BASE_DIR/erts-$ERTS_VSN/bin
-NODETOOL="$ERTS_PATH/escript $RUNNER_BASE_DIR/releases/$APP_VSN/nodetool $NAME_ARG $COOKIE_ARG"
-unset LOCAL_ERL_PATH
-
-# Setup additional arguments for slim release
-SLIM_ARGS="-boot_var RELTOOL_EXT_LIB $RUNNER_BASE_DIR/lib -sasl releases_dir \"$RUNNER_BASE_DIR/releases\""
+# Setup remote shell command to control node
+REMSH="$ERTS_PATH/erl -hidden $REMSH_NAME_ARG $REMSH_REMSH_ARG $COOKIE_ARG"
 
 # Common functions
 
@@ -246,54 +293,7 @@ case "$1" in
         exec $ERTS_PATH/to_erl $PIPE_DIR
         ;;
 
-    eval)
-        # Make sure a node IS running
-        ping_node > /dev/null 2>&1
-        ES=$?
-        if [ "$ES" -ne 0 ]; then
-            echo "Node is not running!"
-            exit $ES
-        fi
-
-        shift
-        $NODETOOL eval "$1"
-        ;;
-
     remote_console)
-        # Test if REMSH_NAME contains a @ and set REMSH_HOSTNAME_PART
-        # and REMSH_NAME_PART according REMSH_TYPE
-        MAYBE_FQDN_HOSTNAME=`hostname`
-        HOSTNAME=`echo $MAYBE_FQDN_HOSTNAME | awk -F. '{print $1}'`
-
-        REMSH_HOSTNAME_PART="$MAYBE_FQDN_HOSTNAME"
-        case "$REMSH_NAME" in
-            *@*)
-                REMSH_HOSTNAME_PART=`echo $REMSH_NAME | awk -F@ '{print $2}'`
-                REMSH_NAME_PART=`echo $REMSH_NAME | awk -F@ '{print $1}'`
-                ;;
-            *)
-                REMSH_NAME_PART="$REMSH_NAME"
-                if [ "$REMSH_TYPE" = "-sname" ]; then
-                    REMSH_HOSTNAME_PART="$HOSTNAME"
-                else
-                    # -name type, check if `hostname` is fqdn
-                    if [ "$MAYBE_FQDN_HOSTNAME" = "$HOSTNAME" ]; then
-                        echo "Hostname must be a fqdn domain name when node is configured with long names"
-                        echo "and the full node name isn't configured in vm.args"
-                        exit 1
-                    fi
-                fi
-                ;;
-        esac
-
-        # Note the `date +%s`, used to allow multiple remsh to the same node
-        # transparently
-        REMSH_NAME_ARG="$REMSH_TYPE remsh`date +%s`@$REMSH_HOSTNAME_PART"
-        REMSH_REMSH_ARG="-remsh $REMSH_NAME_PART@$REMSH_HOSTNAME_PART"
-
-        # Setup remote shell command to control node
-        REMSH="$ERTS_PATH/erl -hidden $REMSH_NAME_ARG $REMSH_REMSH_ARG $COOKIE_ARG"
-
         # Make sure a node is running
         ping_node
         ES=$?
@@ -396,7 +396,7 @@ case "$1" in
         echo $PID
         ;;
     *)
-        echo "Usage: $SCRIPT {start|start_boot <file>|foreground|stop|restart|reboot|ping|console|getpid|console_clean|console_boot <file>|attach|eval|remote_console|upgrade}"
+        echo "Usage: $SCRIPT {start|start_boot <file>|foreground|stop|restart|reboot|ping|console|getpid|console_clean|console_boot <file>|attach|remote_console|upgrade}"
         exit 1
         ;;
 esac
